### ISSUE TITLE
Load image thumbnails alongside comments in user page

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#13]
### Todo
- [x] Call image endpoint to grab the image by ID
- [ ] #289
- [x] Using the image grabbed from response, place it either on left side of the comment box or on the right side
- [x] Consider batching requests so that if multiple comments were written for one image, that image is only retrieved once. (ie. each image request should be unique) - edit: browsers (FF, Chrome, and Safari tested) should do this already
- [x] ~Refactor `generateCommentHTML`~ this is sufficient for now
- [x] If image has been removed, indicate as such instead of leaving it as failed image load
- [x] Add tests
