### ISSUE TITLE
Check for username after username is typed in register screen

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#14]
If username is not taken, checkmark appears beside the input field.
If username is taken, X appears beside input field and error text appears below saying "Username is taken"

### Todo
- [x] Create endpoint `/check_username` which will check supplied username against all usernames in the database
- [x] Add rate limiter to the endpoint to prevent rapid repeated requests
    - ~https://www.npmjs.com/package/express-slow-down~ (edit: express-rate-limit does the job for now)
    - https://www.npmjs.com/package/express-rate-limit (already in project)
- [x] ~Prevent user enumeration attacks by providing CAPTCHA after a certain number of requests are sent from a particular address. If CAPTCHA passes, provide the response, if it fails, then provide a failure response.~
    - ~https://www.rapid7.com/blog/post/2017/06/15/about-user-enumeration/~
    - ~https://security.stackexchange.com/a/123464~
    - ~https://www.google.com/recaptcha/about/~
    **Edit:** This portion has been split off into #256 due to scope.
- [x] Add integration tests and unit tests if applicable (ideally do TDD approach and add these first, then add functionality to satisfy the test conditions)
- [x] Add frontend features described in the issue (ie. ~checkmark~ (edit: green highlight around text field is sufficient) and ~X icons beside the username field~)
