### ISSUE TITLE
Resize images for preview

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#19]
Create two resized copies of each image uploaded
- one for image page, which would have a maximum size that the page can handle without requiring the user to scroll to see the whole image
- one for image preview (e.g. in user's profile page, search, etc.)

The original image can still be viewable by the user when they click on the image in the image page, which will bring up the original image file itself on the browser.

I think this library can be used to accomplish this (but if there's another library that turns out to be more suitable use that instead)
https://github.com/lovell/sharp

# TODO
- [ ] Consider `sharp` library for resizing image for preview
- [ ] Implement image resizing into server-side, consider caching result into db
- [ ] For pages outside image page (ie. user's profile page), use the image preview
- [ ] For the image page, continue using original image file, just resize it using CSS/HTML/JS based on image dimensions and dimensions of page
