### ISSUE TITLE
Improve test suites

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#20]
Implement the remaining tests that have yet to be implemented, and see if there's anything else in the simpleimage codebase that has yet to been tested.

# TODO
- [ ] Finish these tests:
    - [ ] `comments_test`
    - [ ] `log_test`
    - [ ] `user_images_test`
    - [ ] `util_test`
- [ ] Add new tests for uncovered areas
    - [ ] db ops tests
    - [ ] id gen (short id) generation
    - [ ] if there's anything else that can have tests easily added, do those too
- [ ] Introduce CI

**Comment by Coteh** [comment]
Being worked on in #91.
