### ISSUE TITLE
Add Evaluation Mode

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#251]
### Todo
- [ ] Add "Evaluation Mode" - to be enabled via feature flag
- [ ] When this mode is enabled, any image uploaded will be automatically removed after 5-10 minutes
- [ ] Ensure any caches of image need to be revalidated if request is made again to the image

**Comment by mayankbucha** [comment]
Hi @Coteh, this looks like good enhancement. Can I take this up next?

**Comment by Coteh** [comment]
Hey @mayankbucha! Yes sure you can take it. :)

**Comment by mayankbucha** [comment]
Hi @Coteh, how should I go forward with the auto remove feature of Images. I am thinking of creating a new collection (`image-entries-evaluation`) which will have a TTL index. So, when the evaluation flag will be enabled, our images will be stored in this collection, otherwise images will be stored on the current `image-entries` collection. In the `image-entries-evaluation` collection  index, we can add `expireAfterSeconds `to be 300 or any other as a constant that can be set through env file.

**Comment by Coteh** [comment]
Hey @mayankbucha I think it might actually be possible to instead create a partial index on the original `image-entries` collection, something like:

```
collection.createIndex({ uploadeddate: 1 }, { 
    name: "expire_index",
    expireAfterSeconds: 300, // the constant would be put here
    partialFilterExpression: {
        temp: {
            $eq: true,
        }
    } 
}
```

If my understanding is correct, with this index set for `uploadeddate` property (which is a Date object), and with the partial filter expression set on a new field name which I call here `temp`, then any new image that's added with `temp` set to `true` will be removed after 5 minutes.

You will also need to create the `image-entries` collection on startup, as well as create this index once the collection is created. I perform initialization of this sort of stuff inside `startDatabaseClient` function inside `database-ops.js`. It's been a long time since I initially wrote that function, feel free to clean it up to make it Promise-based if you want, since it seems like we'll need to now have both the users collection and the image-entries collection to be created before `finishInitialization` can be called. (which calls the callback that runs the server)

**Comment by mayankbucha** [comment]
Great!! It will be much easier and cleaner with partial index.
