### ISSUE TITLE
Add basic image editing features

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#252]
Create a basic image editor using OpenCV or Pillow (https://pillow.readthedocs.io/en/stable/index.html) for the backend

### Todo
- [ ] Decide on backend to use (Pillow seems like a good choice, but maybe there's a Node library that can be used as well)
- [ ] Sketch out how the UI for this would look
- [ ] Create subissues for other things that would need to be added
- [ ] Write some integration tests and unit tests if applicable
- [ ] Modifications to image would either be saved on top of the image, or can be versioned on top (may require a new issue to be created if images should be versioned)

Issue can be closed when initial work is done and the remaining work has been split off into separate issues.
