### ISSUE TITLE
Add Signup to Upload Images mode

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#253]
Add feature flag that only permits registered users to upload image if enabled.

### Todo
- [ ] Add feature flag
- [ ] If enabled, check if user is guest - if they are, then present login dialog saying you must login to continue
- [ ] Add integration tests and unit tests if applicable
- [ ] `/upload` endpoint should also fail if user is not logged in (check the session)

**Comment by mayankbucha** [comment]
Hi @Coteh, I would like to take this issue next. Should feature flag be enabled through environment variable?

**Comment by Coteh** [comment]
Hey @mayankbucha, go for it! Yes I think for now it can be an environment variable.

**Comment by mayankbucha** [comment]
Hey @Coteh, if the user is not logged in, should the explorer window also be allowed to open when the user clicks the `select-button` or just need to present login dialog when user clicks the `upload-button`.

**Comment by Coteh** [comment]
Login dialog should be shown instead of explorer window yes. :)

**Comment by mayankbucha** [comment]
To do this, first we need to check if the user is logged in from the frontend (`file-upload.js`). I am having difficulty in getting this information. Should we send a request to the server on click of `select-button` or `upload-button` or should we check directly from html if `guest-menu` id is present instead of `user-menu` id? Is there a better way we can do it?

**Comment by Coteh** [comment]
I think sending a request on click, like you mentioned, is the way I'd approach it. I think this is how I'd approach it:

1) Create a new GET route called `/user` - it will make a call to `handleSession` to get the user session. Take a look at some of the other routes in `route.js` to see how this is done.
2) Supplied callback to `handleSession` will get called with user session. Return user info as JSON response if successful, otherwise return an error response (ie. if user is logged out or there was an error getting session)
3) On frontend: If user info is returned, then user will be able to upload image (ie. upload dialog will appear). Otherwise, present login dialog.

Hope this helps!

Also: I think this check should be performed on both the choose button and the upload button. But, once it's acknowledged that user is logged in, it doesn't need to be checked again. (e.g. if choose button is clicked and user is logged in, then clicking upload button will not trigger the check again unless page is refreshed)

**Comment by mayankbucha** [comment]
Thanks for the explanation!! It really clears the approach.
